### ISSUE TITLE
cbrrr v1.0

### ISSUE THREAD

**Issue by DavidBuchanan314** [DavidBuchanan314/dag-cbrrr#1]
Here's all the things I want to complete before it's ready for a v1.0 release:

- [x] Implement parsing into "atjson" format (`$link`, `$bytes`)
- [x] Implement base32 encode/decode in C (to optimise perf in atjson mode)
- [x] Clean up any (important) TODOs in the source
- [x] Rename "parse" to "decode"
- [x] Clean up the CID class, audit correctness
- [x] Robust testing, within a proper testing framework Edit: I'm marking this as done, but there's lots of room for improvement
- [x] Set up a fuzz harness
- [x] Automate testing on GHA
- [x] Figure out some standard benchmarks, show off perf vs `dag_cbor`, `libipld` - done at https://github.com/DavidBuchanan314/dag-cbor-benchmark although some more atproto-specific tests would be good
- [x] Documentation - the API is simple enough that a good README should be enough
- [x] Address https://github.com/DavidBuchanan314/dag-cbrrr/issues/5
- [x] Get it on pypi

Deferred to 1.x:

- [ ] More test coverage
- [ ] GHA testing on macos and windows, and aarch64 if I can figure that out.
- [ ] GHA cross-platform builds and pypi upload
- [ ] Test edge-cases that might arise on 32-bit platforms (and fix any related bugs) https://github.com/DavidBuchanan314/dag-cbrrr/issues/3
- [ ] Optional hard resource limits - recursion depth, number/size of objects allocated https://github.com/DavidBuchanan314/dag-cbrrr/issues/2
- [ ] Parsing into an existing bytearray object, and parsing directly into a new bytes object without copy
- [ ] Implement the CID type entirely in C

**Comment by MarshalX** [comment]
pre-built wheels for all platforms and python versions (uploaded to pypi, automated via GHA)?

**Comment by DavidBuchanan314** [comment]
> pre-built wheels for all platforms and python versions (uploaded to pypi, automated via GHA)?

I'd love to have that but it's not something I know how to do currently, is it maybe something you could help with setting up? I'll put it down as a 1.x goal but that doesn't mean it can't happen sooner (my main aim with 1.0 is to have it ready to use in my PDS rewrite)
